# Generated by Django 4.2 on 2024-09-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Телеграм-ID чата, в который будут отправляться напоминания о выполнении привычки",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Телеграм-ID чата",
            ),
        ),
    ]
