services:
  redis:
    image: redis:latest
    restart: on-failure
  db:
    image: postgres:12.18-alpine
    restart: on-failure
    user: "${UID}:${GID}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    expose:
      - $POSTGRES_PORT
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "-c", "pg_isready -U $POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      network: host
    restart: on-failure
    user: "${UID}:${GID}"
    tty: true
    ports:
      - "8000:8000"
    command: sh -c "poetry run python manage.py migrate &&  poetry run python manage.py collectstatic && poetry run python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/code

  celery:
    build:
      context: .
      network: host
    restart: on-failure
    tty: true
    command: sh -c "poetry run celery -A config worker -l INFO"
    depends_on:
      - redis
      - db
      - app
    volumes:
      - .:/code

  celery-beat:
    build:
      context: .
      network: host
    restart: on-failure
    tty: true
    command: sh -c "poetry run celery -A config beat -l info -S django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - redis
      - db
      - app
    volumes:
      - .:/code

